export const TYPES_COLORS = Object.freeze({
  normal: "bg-normal text-secondary",
  fighting: "bg-fighting text-secondary",
  flying: "bg-flying text-secondary",
  poison: "bg-poison text-primary",
  ground: "bg-ground text-primary",
  rock: "bg-rock text-secondary",
  bug: "bg-bug text-secondary",
  ghost: "bg-ghost text-primary",
  steel: "bg-steel text-secondary",
  fire: "bg-fire text-secondary",
  water: "bg-water text-secondary",
  grass: "bg-grass text-secondary",
  electric: "bg-electric text-secondary",
  psychic: "bg-psychic text-secondary",
  ice: "bg-ice text-secondary",
  dragon: "bg-dragon text-primary",
  dark: "bg-dark text-primary",
  fairy: "bg-fairy text-secondary",
  stellar: "bg-stellar text-secondary",
  unknown: "bg-unknown text-secondary",
});
